### ISSUE TITLE
After docker host update, the Key Vault settings should refresh correctly.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#352]
After update the Docker Host, the Key Vault settings should refresh  just like when going through the manual refresh.
RESULT:
![image](https://cloud.githubusercontent.com/assets/22470312/25209767/aa0579dc-25af-11e7-8a62-a56d247687a0.png)
EXPECT:
![image](https://cloud.githubusercontent.com/assets/22470312/25209875/139c61f8-25b0-11e7-9deb-631a72befbda.png)

**Comment by milismsft** [comment]
This should be fixed in the latest build (checked in the fix after I sent you the email); can you please verify?

Also there seems to be an issue when multiple key vaults are created in the current subscription, the Docker host will wrongly report an error when viewing the details. Can you confirm? I have a fix checked in but it will only be picked up by the build system tomorrow.

**Comment by bsaby** [comment]
Repro,using artifacts/azure-toolkit-for-intellij.2017.342.04-19-2017.zip.

Deploy a Docker host with key vault associaton
Update the docker host
After update, the Key Vault settings content still an error message like above issue
After manually refresh, the the Key Vault settings content is "Not using Key Vault"

**Comment by bsaby** [comment]
Build used:artifacts/WindowsAzurePlugin4EJ.349.04-19-2017.zip
In my tests, after the successful deployment,although the Key Vault created successfully, the detail of  Docker host with Key Vault association are all display unknown. I'm not sure if this is related to the number of key vault created.
![image](https://cloud.githubusercontent.com/assets/22470312/25225266/62c32e2c-25f3-11e7-9f25-1bcdb6779e45.png)
