### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Login fails 

### ISSUE THREAD

**Issue by cglaeser** [microsoft/azure-tools-for-java#6576]
#### Setup

IntelliJ build version: 2022.1 IU-221.5080.210
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.1-2022.1

####  Describe the bug

A clear and concise description of what the bug is, including expected behavior and actual behavior

Login with IntelliJ into Azure is not possible: I can login in the web browser, but the credentials are not forwarded to IntelliJ.

I tried: Device Login and OAuth 2.0 methods. Both login fine in the browser, but IntelliJ does not detect the successful login (OAuth) or is stuck at the login. 

Steps tried to fix: 
-Update IntelliJ + all plugins (no success, now IntelliJ is at 2022.1)
-Restarted computer
-Tried to login to azure with "az login" via terminal (login in terminal is successful, but login into shell is not recognized by IntelliJ)

####  To Reproduce

Login to Azure with either OAuth 2.0 or Device Login. 

Steps to reproduce the bug

#### Exception or Stack Trace

No exception is visible. 

#### Screenshots
![C9CC8A93-B983-4767-AD10-23AA0726A856](https://user-images.githubusercontent.com/1018186/164005065-03a936b9-a02c-4e7a-b5d8-6915fd161232.jpeg)

**Comment by wangmingliang-ms** [comment]
Thanks for reporting, we'll investigate the problem right now. It may take some time for us to reproduce it first.

**Comment by wangmingliang-ms** [comment]
@cglaeser  
Hi, we tested on both M1 and Intel Mac, they are all fine. Can you share your macOS version with me?

**Comment by cglaeser** [comment]
@wangmingliang-ms - Sure, I use Mac OS 12.3.1 (M1)

**Comment by phiroict** [comment]
Same issue here: 
IDEA 2022.1 (Build #IU-221.5080.210, built on April 12, 2022)
Mac OS: 12.3.1 (21E258)
Mac platform M1 - Mac Studio Ultra
Default web handler: Firefox 99.0.1
Same result with Safari : Version 15.4 (17613.1.17.1.13)
Azure plugins: 3.63.1-2022.1
No errors shown, one line in the logfiles.
Now I see that IDEA is processing the return 
![image](https://user-images.githubusercontent.com/3645795/164589705-b64e4f9c-9f0c-460a-a3be-7e238a8a1a6f.png)
but then it fails with no further information, Azure streaming log is empty . 
IntelliJ logs print: (${HOME}/Library/Logs/JetBrains/IntelliJIdea2022.1/idea.log)
```
2022-04-22 15:34:33,148 [16059320] SEVERE - c.a.i.InteractiveBrowserCredential - Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: Failed to acquire token with Interactive Browser Authentication.
```

**Comment by Flanker32** [comment]
@cglaeser @phiroict Thank you all for your help! It seems that authentication library we use have some compatibility issues with Mac, we are working to resolve it. 

As a workaround, could you please try launch the IntelliJ from bash and try azure cli authentication? As IntelliJ launched from Finder may lose some environment variables and make the toolkit count not find azure cli and failed to auth, and launch from bash should resolve this issue, you may find more details in this [blog](https://devkimchi.com/2022/02/04/things-to-know-when-writing-azure-functions-in-java/)

**Comment by cglaeser** [comment]
@Flanker32 Thank you for your response. The workaround works for me.
<img width="519" alt="Screenshot 2022-04-22 at 19 17 55" src="https://user-images.githubusercontent.com/1018186/164763894-8fb6efa8-ec8b-4205-860c-871c9712e242.png">
<img width="1155" alt="Screenshot 2022-04-22 at 19 18 09" src="https://user-images.githubusercontent.com/1018186/164763903-e6e06a22-87a9-45a1-aefc-df807f7cc10c.png">

**Comment by dkontyko** [comment]
Not sure if I missed a step. but I can't find a way to enable the Azure CLI option on the Sign In selection screen. (OAuth and Device Login fail for me with the same symptoms above.) A successful workaround for me was creating a service principal in my tenant and authenticating with that.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/33853225/168448806-b3288957-30df-4b65-ab62-e415329fc9f5.png">

IntelliJ IDEA 2022.1.1 (Ultimate Edition) Build #IU-221.5591.52, built on May 10, 2022
macOS 12.3.1
Azure Functions Core Tools
Core Tools Version:       4.0.4483 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.1.3.17473
Azure Toolkit plugin 3.64.0-2022.1

Launching from Terminal (zsh) doesn't enable the Azure CLI option, either.

Is this related to [this issue](https://github.com/JetBrains/azure-tools-for-intellij/issues/514) by chance?

**Comment by moabduikea** [comment]
> 
The same issue and also I can't login to My Azure account

**Comment by wangmingliang-ms** [comment]
@dkontyko Did you login to Azure CLI first?

You need to log in to the Azure CLI first, then start IntelliJ IDEA from shell and log in as described above, and you should see that the Azure CLI login method is enabled.

**Comment by moabduikea** [comment]
Yes I did but still the same issue.

Thank you and Regards,
---------------------------------------------------------
Mohammed Abdu | Senior Java Developer
IKEA Saudi and Bahrain
----------------------------------
Mobile: +20 11 100 76777
Email:   ***@***.***
Web:     www.IKEA.com.sa<http://www.IKEA.com.sa>

***@***.***


From: Miller Wang ***@***.***>
Date: Monday, 16 May 2022 at 3:39 PM
To: microsoft/azure-tools-for-java ***@***.***>
Cc: Mohamed Abdu ***@***.***>, Comment ***@***.***>
Subject: Re: [microsoft/azure-tools-for-java] [IntelliJ][ReportedByUser] Azure Login fails (Issue #6576)

@dkontyko<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdkontyko&data=05%7C01%7CMohamed.Abdu%40PROGBSC.com%7C61a853f511ec46564e7208da37418d0b%7C7ddcd412aa67423eb6d78a90efbeeeb9%7C1%7C0%7C637883051954767674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GBNoAuE%2BGGxIDwZt2lfR0Q0X%2BrEXG5WXONuyA%2Brd%2BFk%3D&reserved=0> Did you login to Azure CLI first?

You need to log in to the Azure CLI first, then start IntelliJ IDEA from shell and log in as described above, and you should see that the Azure CLI login method is enabled.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazure-tools-for-java%2Fissues%2F6576%23issuecomment-1127689474&data=05%7C01%7CMohamed.Abdu%40PROGBSC.com%7C61a853f511ec46564e7208da37418d0b%7C7ddcd412aa67423eb6d78a90efbeeeb9%7C1%7C0%7C637883051954767674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SSPHQTVN8OnkG8g65702J8cFD80372uHp2IdHZyAEfM%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYOFDEKRIKT6I3XLQFDH3V3VKJF2LANCNFSM5TYW46JA&data=05%7C01%7CMohamed.Abdu%40PROGBSC.com%7C61a853f511ec46564e7208da37418d0b%7C7ddcd412aa67423eb6d78a90efbeeeb9%7C1%7C0%7C637883051954767674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wPa8s%2FiLAeGL7vUhyJz1RpTdQSZDFkFFF4BxtCcOOm0%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>



تنبيه: هذه الرسالة تم إرسالها من خارج الشركة. الرجاء عدم فتح أي رابط أو مرفقات إلا بعد التأكد من المُرسِل والمحتوى
 CAUTION: This email originated from outside organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by Flanker32** [comment]
@cglaeser @phiroict @dkontyko @moabduikea Thanks a lot for your help! We have released the fix of this issue to dev channel, could you please try the bits and see whether the issue could be produces? You may get the bits [here](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij/versions/dev)

**Comment by dkontyko** [comment]
@Flanker32 sorry for the delay, this fixed OAuth login to the Azure Tools in IntelliJ, so I can see my subscription resources, etc. However, debugging a Function that uses the Default Azure Credential to connect to Azure Storage still fails in IntelliJ. Do you know if this is expected to work while debugging within IntelliJ, or is this by design?

Specific call that is throwing the exception: https://github.com/dkontyko/RestPdfFormFiller/blob/f46cc11f360d30d867441bbdcceb4ecb9c0d5896/src/main/java/app/djk/RestPdfFormFiller/functions/FileSessions.java#L59

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/33853225/174171143-dd0caabb-4e70-4a63-9e71-7f9485721182.png">

Thank you for all your help with this issue.

**Comment by Flanker32** [comment]
@dkontyko Currently IntelliJ Authentication in `DefaultAzureCredential` is broken as we have migrated to msal but identity still leverage the old credential, we will work with identity team to fix this issue later. As a workaround, you may auth with Azure Cli/VSCode and `DefaultAzureCredential` should works in this case. For Azure environment, you could use Managed Identity for authentication, please refer this [doc ](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Cjava#connect-to-azure-services-in-app-code) for details.

Besides, you may also use connection string to build a blob client, here is the related [doc](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java?tabs=powershell%2Cenvironment-variable-windows). Or you may also leverage Azure Function to upload files to blob, and [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-output?tabs=in-process%2Cextensionv5&pivots=programming-language-java) is the related doc.
